### ISSUE TITLE
Pb with mps

### ISSUE THREAD

**Issue by edljk** [Joel-Dahne/MethodOfParticularSolutions.jl#1]
I tried to reproduce the example

```julia
using MethodOfParticularSolutions, Nemo, ArbTools, Plots, LaTeXStrings
RR = ArbField(53)
setprecision(BigFloat, 53)
domain = LShape(RR)
u = LShapeEigenfunction(domain)
N = 15
λs = range(1, stop = 20, length = 200)
σs = [sigma(λ, domain, u, N) for λ in λs]
N = 15
interval = setinterval(RR(9), RR(10))
(λ, _) = mps(domain, u, interval, N)
```
and obtained the following error calling `mps`

```julia
ERROR: LoadError: MethodError: no method matching iterate(::arb)
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:600
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:600
  iterate(::ExponentialBackOff) at error.jl:218
```
I should add that `ArbTools` seems to be well installed since I obtained no errors during the tests of the package.
Thanks!

**Comment by Joel-Dahne** [comment]
The issue was that the example was based on an old version of the package. Previously `mps` returned both the eigenvalue `λ` and the eigenfunction `u` but it now only returns the eigenvalue. The README has been updated accordingly and now it should hopefully work!

While at it I'll try to add an example of some higher precision computations to the README, likely later today.
